### ISSUE TITLE
Vector in wrong place?

### ISSUE THREAD

**Issue by dellaert** [borglab/SwiftFusion#196]
https://github.com/borglab/SwiftFusion/blob/4ae925cd2759e4fccc7578c076cb4f71f782b003/Sources/SwiftFusion/Core/FixedSizeMatrix.swift#L403

Seems Vector extension is misplaced in FixedSizeMatrix.swift? At least, I was surprised to find it there :-)

**Comment by ProfFan** [comment]
It's a fileprivate (not exposed) helper for easy implementation of Matrix operations (see the comments)

**Comment by dellaert** [comment]
OK, makes sense
