### ISSUE TITLE
inverse: top-level function or method?

### ISSUE THREAD

**Issue by marcrasi** [borglab/SwiftFusion#22]
Is there a strong reason to have `inverse: Rot2 -> Rot2` and `inverse: Pose2 -> Pose2` being top-level functions?

If not, I'd like to change them to methods on `Rot2` and `Pose2` because that's more standard Swift API style (https://swift.org/documentation/api-design-guidelines/#general-conventions => "Prefer methods and properties to free functions.")

A practical motivation is that Swift overload resolution produces confusing error messages when there are a lot of top level functions with the same name floating around.

**Comment by ProfFan** [comment]
I agree :)
