### ISSUE TITLE
SwiftFusion on Mac Issue

### ISSUE THREAD

**Issue by dellaert** [borglab/SwiftFusion#241]
I installed latest development toolchain (Nov 17), and using latest Xode Version 12.2 (12B45b), which I pointed to the toolchain.

But even before that, I cannot generate the project, as it complains about Benchmarks package
```
(base) iOmega:~ dellaert$ which swift
/Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-11-17-a.xctoolchain/usr/bin//swift
(base) iOmega:~ dellaert$ cd git/SwiftFusion/
(base) iOmega:SwiftFusion dellaert$ swift package generate-xcodeproj
Updating https://github.com/google/swift-benchmark.git
Updating https://github.com/saeta/penguin.git
Updating https://github.com/apple/swift-tools-support-core.git
Updating https://github.com/tensorflow/swift-models.git
error: swift-benchmark is required using two different revision-based requirements (f70bf472b00aeaa05e2374373568c2fe459c11c7 and master), which is not supported
error: multiple targets named 'Benchmarks' in: Penguin, swift-models
```
@ProfFan @marcrasi , help? We did *something* the last time this happened, but I forget what, and this probably needs a different fix.

**Comment by ProfFan** [comment]
This can be solved by changing Penguin. Let me put a PR there.

**Comment by ProfFan** [comment]
#242 should make everything work :) Please test @dellaert

**Comment by ProfFan** [comment]
I just updated to Big Sur and confirm that everything works with XCode 12.2 release and 0.12 toolchain. You will need the following workaround (only once after install):
```
sudo install_name_tool -add_rpath /Applications/Xcode.app/Contents/Developer/Library/Frameworks/ /Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.12.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB
```

**Comment by dellaert** [comment]
I still have
```
Current branch master is up to date.
(base) iOmega:SwiftFusion dellaert$ swift package generate-xcodeproj
Updating https://github.com/saeta/penguin.git
Updating https://github.com/apple/swift-tools-support-core.git
Updating https://github.com/tensorflow/swift-models.git
Updating https://github.com/google/swift-benchmark.git
Updating https://github.com/apple/swift-argument-parser
Updating https://github.com/ProfFan/tensorboardx-s4tf.git
Fetching https://github.com/apple/swift-protobuf.git
Removing https://github.com/vojtamolda/Plotly.swift
Resolving https://github.com/tensorflow/swift-models.git at b2fc0325bf9d476bf2d7a4cd0a09d36486c506e4
Resolving https://github.com/google/swift-benchmark.git at master
Resolving https://github.com/apple/swift-argument-parser at main
Cloning https://github.com/apple/swift-protobuf.git
Resolving https://github.com/apple/swift-protobuf.git at 1.13.0
error: multiple targets named 'Benchmarks' in: Penguin, swift-models
warning: dependency 'swift-argument-parser' is not used by any target
```

**Comment by ProfFan** [comment]
@dellaert Please try the following:
1. Make sure that you have XCode 12.2 Release or 12.2 Beta 3
2. Make sure you have latest toolchain by re-downloading the 0.12 toolchain on the S4TF GitHub
3. Remove `.build`
4. Make sure you have latest `feature/ppca` by `git pull`
5. `export PATH=/Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.12.xctoolchain/usr/bin:$PATH`
6. `sudo install_name_tool -add_rpath /Applications/Xcode.app/Contents/Developer/Library/Frameworks/ /Library/Developer/Toolchains/swift-tensorflow-RELEASE-0.12.xctoolchain/System/Library/PrivateFrameworks/LLDB.framework/Versions/A/LLDB`
7. `swift package generate-xcodeproj`
8. Open the XCode project, you should be able to build and test

**Comment by ProfFan** [comment]
Additional Note:

If you have a problem where XCode is trying to build ARM64, follow the following picture:
![image](https://user-images.githubusercontent.com/5358374/100168342-1310c800-2e8f-11eb-8d10-71941ec777c4.png)

Change `Excluded Architectures` to `arm64` and everything should work flawlessly.

**Comment by dellaert** [comment]
I did everything except instead of 0.12 I used the 11-17 development snapshot. I got this error:
```
Ld /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-egqwofyvxltxgzagbkenjuugmcfz/Build/Products/Debug/CPenguinParallel.framework/Versions/A/CPenguinParallel normal (in target 'CPenguinParallel' from project 'SwiftFusion')
    cd /Users/dellaert/git/SwiftFusion
    /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-11-17-a.xctoolchain/usr/bin/clang -target x86_64-apple-macos10.10 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -L/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-egqwofyvxltxgzagbkenjuugmcfz/Build/Products/Debug -F/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-egqwofyvxltxgzagbkenjuugmcfz/Build/Products/Debug -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -filelist /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-egqwofyvxltxgzagbkenjuugmcfz/Build/Intermediates.noindex/SwiftFusion.build/Debug/CPenguinParallel.build/Objects-normal/x86_64/CPenguinParallel.LinkFileList -install_name @rpath/CPenguinParallel.framework/Versions/A/CPenguinParallel -Xlinker -rpath -Xlinker /Library/Developer/Toolchains/swift-tensorflow-DEVELOPMENT-2020-11-17-a.xctoolchain/usr/lib/swift/macosx -Xlinker -object_path_lto -Xlinker /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-egqwofyvxltxgzagbkenjuugmcfz/Build/Intermediates.noindex/SwiftFusion.build/Debug/CPenguinParallel.build/Objects-normal/x86_64/CPenguinParallel_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-egqwofyvxltxgzagbkenjuugmcfz/Build/Intermediates.noindex/SwiftFusion.build/Debug/CPenguinParallel.build/Objects-normal/x86_64/CPenguinParallel_dependency_info.dat -o /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-egqwofyvxltxgzagbkenjuugmcfz/Build/Products/Debug/CPenguinParallel.framework/Versions/A/CPenguinParallel

ld: unknown option: -no_adhoc_codesign
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by dan-zheng** [comment]
Jumping in: I have some experience with Swift and Xcode on macOS. Happy to call if you'd like to chat, send me a calendar invite.

**Comment by dellaert** [comment]
Cool, left you a chat msg, G-side

**Comment by dan-zheng** [comment]
Follow-up: we figured out @dellaert's problem! It's because he had the wrong Xcode Command Line Tools selected.

You can fix that via Xcode's GUI:

<img src="https://user-images.githubusercontent.com/5590046/100543477-73e92900-321e-11eb-8bbf-f63c65947555.png" width=60%>

Or via the command-line:
```console
$ sudo xcode-select /Applications/Xcode.app # make sure it's the same Xcode that you have open right now
```

---

You may also encounter weird build issues related to Swift project shenanigans. A _clean build_ may fix these issues.

There are two ways to open SwiftPM packages like SwiftFusion:

1. SwiftPM-first workflow: use SwiftPM to generate an Xcode project. This seems more stable, but apparently [it's becoming deprecated](https://forums.swift.org/t/rfc-deprecating-generate-xcodeproj/42159).

```console
$ swift package generate-xcodeproj
$ open SwiftFusion.xcodeproj
# Within Xcode, build project (⌘B).
```

2. Xcode-first workflow. Open `Package.swift`, either via `open Package.swift` in the terminal or by double-clicking on it in Finder. Xcode should open the package, then download 

The first method (SwiftPM) is more reliable in my experience, even though it's getting deprecated. I hope Xcode's SwiftPM continues to get more robust.

In the meantime, if you encounter issues, I'd recommend just wiping all build and cached artifacts from (1) and (2).

```console
# Wipe SwiftPM stuff.
rm -rf .build
rm -rf Package.resolved # This is like CMakeCache.txt or yarn.lock. Generally should be safe to delete.

# Wipe Xcode stuff.
rm -rf ~/Library/Developer/Xcode/DerivedData
```
