### ISSUE TITLE
main does not compile on XCode/M1

### ISSUE THREAD

**Issue by dellaert** [borglab/SwiftFusion#256]
For fun, without it expecting to work, I did try compiling main on my new M1 Mac Mini, Latest Xcode 12.2 (12B45B) from App Store. Results below:

![image](https://user-images.githubusercontent.com/10515273/102091576-011aa900-3ded-11eb-88cd-0e2ececdbbe8.png)

**Comment by dan-zheng** [comment]
Thanks for sharing! I wonder what are the compilations errors?

**Comment by dellaert** [comment]
@dan-zheng 
seems to be a segmentation fault.

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'SwiftFusion' from project 'SwiftFusion')
    cd /Users/dellaert/git/SwiftFusion
    export DEVELOPER_DIR\=/Applications/Xcode.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name SwiftFusion -Onone -enable-batch-mode -enforce-exclusivity\=checked @/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/arm64/SwiftFusion.o.SwiftFileList -DSWIFT_PACKAGE -DDEBUG -Xcc -fmodule-map-file\=/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/GeneratedModuleMaps/CPenguinParallel.modulemap -DXcode -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -target arm64-apple-macos10.14 -g -module-cache-path /Users/dellaert/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -enable-testing -index-store-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Index/DataStore -swift-version 5 -I /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug -I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/usr/lib -F /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug -F /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/Library/Frameworks -c -j8 -output-file-map /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/arm64/SwiftFusion-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/arm64/SwiftFusion.swiftmodule -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/swift-overrides.hmap -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/SourcePackages/checkouts/penguin/Sources/CPenguinParallel/include -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Products/Debug/include -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/DerivedSources-normal/arm64 -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/DerivedSources/arm64 -Xcc -I/Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/DerivedSources -Xcc -DSWIFT_PACKAGE -Xcc -DDEBUG\=1 -emit-objc-header -emit-objc-header-path /Users/dellaert/Library/Developer/Xcode/DerivedData/SwiftFusion-dlztdegpemgnnmclvvxqgnrvizyk/Build/Intermediates.noindex/SwiftFusion.build/Debug/SwiftFusion.build/Objects-normal/arm64/SwiftFusion-Swift.h -working-directory /Users/dellaert/git/SwiftFusion

<unknown>:0: error: unable to execute command: Segmentation fault: 11
<unknown>:0: error: compile command failed due to signal 11 (use -v to see invocation)
