### ISSUE TITLE
Removing swift-apis or s4tf/s4tf dependency

### ISSUE THREAD

**Issue by philipturner** [borglab/SwiftFusion#274]
Keeping this off the [Swift Forums thread](https://forums.swift.org/t/ongoing-work-on-differentiable-swift/57780/4) to prevent from polluting it. The Cholesky and SVD operators used by SwiftFusion have been troubling me for a while, and it would be awesome if I could remove them from S4TF. I don’t know whether it’s possible to remove the entire dependency to S4TF. But if you could at least substitute those two operators with a third-party library, it would make creating Metal and OpenCL backends for S4TF easier. It would also consolidate the operator set to stuff strictly related to deep learning.

Also I have a build script for compiling S4TF with the newest TF version, although there’s [a crash](https://github.com/s4tf/s4tf/issues/14) if you try using graph mode with XLA. I would be happy to help you compile SwiftFusion again, as I haven’t compiled any third-party library depending on S4TF yet - not even [swift-models or s4tf/models](https://github.com/s4tf/models). You would need to either (1) change SwiftFusion to build via SwiftPM or (2) make a PR to [s4tf/s4tf](https://github.com/s4tf/s4tf) for revived CMake support.

**Comment by philipturner** [comment]
CC: @ProfFan

**Comment by ProfFan** [comment]
Thank you for the effort Philip! I think the safe way now is moving away to the Tensor I/F, so I'll close this for now :)

**Comment by philipturner** [comment]
I'm no longer working on S4TF and the Swift Numerics Workgroup seems to have slowly faded away, so you're probably going to be alone if working on this. I recommend just using a system BLAS library to implement matrix multiplications. For M1, the AMX accelerator available from a single-core CPU context provides up to ~1-2 TFLOPS, depending on the chip.

Also, Swift 5.7 has been released. I have not tested AutoDiff since back during v5.7 beta, but it probably works. You may have to do some compiler engineering to fix bugs, or reach out to PassiveLogic for help. Note that release toolchains lag behind top-of-tree toolchains by a few months, regarding bug fixes.

Also, Swift-Colab is still being maintained because I use it personally. It should serve as a good platform for testing stuff out on Linux. Mostly because it takes ~20 seconds to download a Swift toolchain from Google's servers, while your personal computer takes minutes. The Bash scripting capabilities were enhanced with v2.2-3 to make the experience as good as with Python Jupyter notebooks.
