### ISSUE TITLE
LeastSquaresObjective: decoupling the CGLS optimizer from the factor graph representation

### ISSUE THREAD

**Issue by marcrasi** [borglab/SwiftFusion#28]
I have been thinking about @dellaert's comments during our last chat that CGLS is particularly suited to SwiftFusion because CGLS only needs the JVP and VJP. CGLS does not need to know anything about the internals of the factor graph as long as the factor graph can (efficiently) produce JVP and VJPs.

It would be good to encode this idea in an interface, so that we can code CGLS once against this interface and then experiment with various ways of writing factor graphs without having to change the CGLS implementation.

Here's a proposal for an interface. (I typed in all the code without running it through the compiler, so there may be silly errors.)

# Interface

```swift
/// A least squares objective function.
///
/// The objective is to find values `v` that minimize the sum of squares of
/// `errors(at: v)`.
protocol LeastSquaresObjective {
  /// The type of the input to the objective function.
  associatedtype Values: Differentiable

  /// Returns a vector of errors. The objective is to minimize the sum of
  /// squares of these errors.
  func errors(at values: Values) -> Tensor<Double>

  /// The type of the linearized objective.
  associatedtype Linearized: LinearLeastSquaresObjective
    where Linearized.Values == Values.TangentVector

  /// Returns this objective linearized around `values`.
  ///
  /// The `w` method of the linearized objective is the "Jacobian Vector
  /// Product" (JVP) of `errors` at `values`.
  ///
  /// The `wDual` method of the linearized objective is the "Vector Jacobian
  /// Product" (VJP) of `errors` at `values`.
  func linearized(around values: Values) -> Linearized
}

/// A linear least squares objective function.
///
/// The objective is to find values `v` that minimize the sum of squares
/// of `w(v) - b`.
protocol LinearLeastSquaresObjective {
  /// The type of the input to the objective function.
  associatedtype Values: AdditiveArithmetic

  /// A linear transformation of the input values.
  ///
  /// When this objective was obtained by linearizing a nonlinear objective,
  /// this is the "Jacobian Vector Product" (JVP) of the nonlinear objective
  /// `errors` around the linearization point.
  func w(_ v: Values) -> Tensor<Double>

  /// The dual of `w`.
  ///
  /// When this objective was obtained by linearizing a nonlinear objective,
  /// this is the "Vector Jacobian Product" (VJP) of the nonlinear objective
  /// `errors` around the linearization point.
  func wDual(_ v: Tensor<Double>) -> Values

  /// The value that we are trying to get `w(v)` close to (in Euclidean
  /// distance).
  var b: Tensor<Double> { get }
}
```

# Optimizers programmed against this interface

Here's a rough implementation of gradient descent written against this interface, to illustrate how the interface works.

```swift
func gradientStep<Objective: LeastSquaresObjective>(
  _ values: inout Objective.Values,
  _ objective: Objective
) {
  let learningRate = Double(0.1)
  let linearized = objective.linearized(around: values)
  let gradient = linearized.wDual(linearized.b)
  values.move(along: gradient.scaled(by: -learningRate))
}
```

CGLS would be a bit more complicated and would use both `w` and `wDual`.

# Implementations of this interface

The interface doesn't specify anything about how the objective is represented, so we can try a lot of different things:

 * different ways of encoding sparsity,
 * different ways of computing derivatives (e.g. use reverse mode for everything now, but switch to forward mode when it works better in Swift),
 * different ways of representing polymorphism (e.g. erase all the types so that the user can use any types as values in the graph vs require the user to specify what types they want to use in their graph up front).

For example, here's an implementation of dense ordinary least squares, which we could use to test things out before we have implementations with more complicated stuff like sparsity and nonlinear factors:

```swift
struct DenseOrdinaryLeastSquares: LeastSquaresObjective, LinearLeastSquaresObjective {
  /// The objective is to minimize the sum of squares of `wMatrix * v - b`.
  var wMatrix, b: Tensor<Double>

  func w(_ v: Tensor<Double>) -> Tensor<Double> {
    matmul(w, v)
  }

  func wDual(_ v: Tensor<Double>) -> Tensor<Double> {
    matmul(wMatrix.transposed(), v)
  }

  func errors(at values: Tensor<Double>) -> Tensor<Double> {
    w(values) - b
  }

  func linearize(around values: Tensor<Double>) -> Self {
    // This objective is already linear, so we can linearize it by returning `self`.
    self
  }
}
```

Do you think this is a good direction, @ProfFan & @dellaert ?

**Comment by dellaert** [comment]
I'll take a detailed look in the morning ;-)

**Comment by ProfFan** [comment]
This is great idea! As we have discussed in the meeting, I am trying to make a skeleton implementation in #23. I kind of struggled a lot to get all the protocol conformances work, but this is definitely a great way to go. I'll think about this tonight and see if I can come up with something tomorrow.

On the assumption that we only need the Jacobian, yes, that is true for CGLS, and if I was not wrong the `HessianFactor` in GTSAM is also converted first into a Jacobian by Cholesky decomposition (correct me if not :) )

**Comment by dellaert** [comment]
I just read through this, and it all sounds reasonable, *but* I don't know why we have to think about this now. I'm actually pretty bad in anticipating what an interface should look like before it is needed. My preferred way of making headway towards that is to be test-driven, and when we add a second optimizer, see what abstraction that imposes... In a way, the added uni tests "atomize" the interface. Perhaps we'll end up in exactly the same place - but my first concern here would to make sure that we get the factor graph API absolutely right, and only then branch out to a more general architecture.
My 2 cts

**Comment by marcrasi** [comment]
Perhaps we are both trying to get at the same thing, but we have different ways of thinking about it. I was trying to figure out what kinds of operations a factor graph needs to support, so that I can start thinking about how to write them.

I did this by writing a generic interface, not because I wanted to start out by writing super general algorithms, but because it's a way to talk about what the factor graph should be able to do before spending time actually implementing it. This approach sort of "isomorphic" to the approach of writing unit tests against the interface, and I'm happy to try expressing my thoughts that way too!

Here's an attempt to express these same thoughts in a unit test: 

```
let graph = makeGraphWithOneVec2VariableAndOnePrior(prior: Vec2(5, 5))
let initialGuess = Values([Vec2(1, 1)])
let linearized = graph.linearize(around: initialGuess)
assertEqual(graph.errors(at: initialGuess), [4, 4])
assertEqual(linearized.b, [4, 4])
assertEqual(linearized.w([1, 0]), [1, 0])
assertEqual(linearized.w([0, 1]), [0, 1])
```

(What goes on in `makeGraphWithOneVec2VariableAndOnePrior` is a very interesting aspect of the factor graph API that I haven't specified in this test yet. I have some thoughts about this that I could write up soon. I can definitely write them in a similar test-driven style.)

Is this kind of what you're looking for when you say we should be test-driven? Or is it something different that I haven't understood?

**Comment by dellaert** [comment]
Yep, indeed. But I think Fan is writing the unit test for CGLS, so CGLS will ask for particular things, like vjp and jvp, maybe other things as well. I’ve asked him to speed things along a bit, see my review of his PR where I added more comments about the need to be generic (or not) at this time.

Note Values above should be able to have 1M things in it, all of different type (I know you know and decided not to tackle that yet), possibly indexed by arbitrary keys. And Vec2 is a special case - better work with Pose2 as it has the appealing property of having a TangentVector type that is not itself.
