### ISSUE TITLE
Type-erased wrapper for differentiable `Value` (a.k.a. `AnyDifferentiable`)

### ISSUE THREAD

**Issue by ProfFan** [borglab/SwiftFusion#30]
I think @marcrasi has mentioned this in an issue, and I encountered this problem in prototyping the nonlinear factor graph API as well.

**Comment by ProfFan** [comment]
#9

**Comment by marcrasi** [comment]
This should happen in the 0.9 release of S4TF. That's a few weeks away, so I can import the code into this repo in the meantime.
