### ISSUE TITLE
Implementation of Gauss-Newton and/or CGLS

### ISSUE THREAD

**Issue by ProfFan** [borglab/SwiftFusion#6]
As discussed with @dellaert, we need to do a TDD-based implementation of Gauss-Newton and Conjugate-Gradient-Least-Squares to assist the design of the library.

**Comment by marcrasi** [comment]
The factor graph defines an objective function for the optimizer, right? Is having a factor graph API (#11) a prerequisite for this? Or is there some other way you want to define the objective function so that the optimizer doesn't depend on the factor graph API?

**Comment by dellaert** [comment]
Indeed. A factor is a pair of a (differentiable) measurement function and a measurement, and I think we need that API in place first. This can be very lightweight, BTW. In C++ it is just a vector of instances derived from "Factor".
