### ISSUE TITLE
Milestone: Pose2SLAM works in SwiftFusion

### ISSUE THREAD

**Issue by marcrasi** [borglab/SwiftFusion#9]
A simple milestone for this project is to get something like https://github.com/borglab/gtsam/blob/develop/cython/gtsam/tests/test_Pose2SLAMExample.py working.

Prerequisites:
* #11: Simple Factor Graph API
* #6: Implementation of Gauss-Newton and/or CGLS
* #12: BetweenPose2 Factor

**Comment by dellaert** [comment]
All, you can find an intro lecture to Pose2SLAM [here](https://gtvault-my.sharepoint.com/:p:/g/personal/fd27_gatech_edu/EQCNT0ZuBRtMlvIVhPoXjVgB4UadpCgaujHyqXyc0kyGXQ?e=PAg0sf). Please forgive my nasal voice: I am suffering from Atlanta pollen !

**Comment by ProfFan** [comment]
I think we are already there!
